### ISSUE TITLE
Review for CRAN release (v.1.0.0)

### ISSUE THREAD

**Issue by karomanchuk** [karissawhiting/cbioportalR#43]
**General Feedback**

- [x]  noticed pipes and pulls are frequently used on the package website in the Examples, but the dplyr package was not mentioned on this page (it is mentioned on the vignette page)– really not a big deal, but for brand new R users it may be helpful to mention that pipes and pulls require dplyr to be loaded, or simply add a line with “library(dplyr)” at the beginning of Example :) 

- [x] Another small thing that you can take or leave: When the df <- get_genetics_by_study(study_id = "acc_tcga") (and subsequently get_mutations_by_study(study_id = "acc_tcga"); get_cna_by_study(study_id = "acc_tcga")) are mentioned, I think that it could be more clearly explained.
e.g., there is a comment “# As a result you will get a list of dataframes of 1) mutation + fusion and 2) can." That is just kind of floating amongst the code – I might suggest attaching this with the get_mutations_by_study() and get_cna_by_study() by saying something along the lines of:
“It can be useful to pull all genomic data for a particular study. To do so, the functions get_mutations_by_study() and get_cna_by_study() can be utilized with a specific study to pull the mutation and cna data respectively. To simultaneously pull the all information (including fusion data) in a list of dataframes, use the get_genetics_by_study() function as detailed below:”

**There were a few discrepancies with outputs in both the package website and the vignette:**

- [x] Website: In the get_mutations_by_sample() my output includes: #>Genes: “All available genes”, but the website has #> Genes: "all IMPACT genes (see `gnomeR::impact_gene_info`)" (This could be related to gnomeR – if this is something relevant come see me and I’ll explain :))
My tibble resulting from mutations %>%
  head() does not match what is on the website (I think it is the same table, just a different order? Not sure if this is important, more of an fyi)

- [x] Vignette: all_studies shows 336 more rows for me, but there are 335 rows on the vignette.

- [x] In the text of the vignette, it does not mention "prad_msk_2019"

**Comment by karissawhiting** [comment]
>  noticed pipes and pulls are frequently used on the package website in the Examples, but the dplyr package was not mentioned on this page (it is mentioned on the vignette page)– really not a big deal, but for brand new R users it may be helpful to mention that pipes and pulls require dplyr to be loaded, or simply add a line with “library(dplyr)” at the beginning of Example :)

I wasn't sure about this but realized I actually export the pipe in the package, so users can use it without loading `dplyr`.  In that case, I think I can leave pipes in examples for now! `pull()` is not exported but I think examples don't have it luckily. 

> Another small thing that you can take or leave: When the df <- get_genetics_by_study(study_id = "acc_tcga") (and subsequently get_mutations_by_study(study_id = "acc_tcga"); get_cna_by_study(study_id = "acc_tcga")) are mentioned, I think that it could be more clearly explained.
e.g., there is a comment “# As a result you will get a list of dataframes of 1) mutation + fusion and 2) can." That is just kind of floating amongst the code – I might suggest attaching this with the get_mutations_by_study() and get_cna_by_study() by saying something along the lines of:
“It can be useful to pull all genomic data for a particular study. To do so, the functions get_mutations_by_study() and get_cna_by_study() can be utilized with a specific study to pull the mutation and cna data respectively. To simultaneously pull the all information (including fusion data) in a list of dataframes, use the get_genetics_by_study() function as detailed below:”

Great catch. The part about mutations + fusions is actually incorrect as well, so fixing this in the latest version. For now I decided to remove this to keep the README simple, and instead direct people to the vignette for more info.
