### ISSUE TITLE
Feedback before submission of v1.0.1

### ISSUE THREAD

**Issue by karissawhiting** [karissawhiting/cbioportalR#50]

**Comment by hfuchs5** [comment]
When I set get_XXX_by_study(study_id = "prad_msk_2019", add_hugo = F), the hugo symbols are still included in the dataset, but when I run these as get_XXX_by_sample(....) it works properly.

**Comment by karissawhiting** [comment]
@hfuchs5 Thank you so much for this feedback, it's super useful!

- **`panel` and `genes` arguments** - The `genes` argument isn't currently available for `get_XXX_by_study()` functions. Pulling by study ID is suppose to return all raw data available (in its entirety including all genes/all samples etc.) for a given study. Pulling by sample ID however gives you more fine-grained control and is particularly useful for pulling across multiple studies at once. In those situations, you may want to be more restricting with which genes you are including, as samples from two different studies may employ different gene panels. I think documentation could definitely be improved explaining this and maybe I can add a warning if someone tries to pass these args?

- **`add_hugo`** - Good point about `add_hugo` that result is confusing. I think this behavior might have changed since the last release of cbioportal (the API now returns hugo symbol by default where it didn't previously) and I may have to adjust. Do you have the example of `add_hugo = FALSE` working properly with `get_XXX_by_sample(....)` that you mentioned? Trying to figure out what is going on. 

Thanks again!! 🎉 🙏

**Comment by hfuchs5** [comment]
Using the same example as your vignette: 

s1 <- available_samples("blca_nmibc_2017") %>%
  select(sampleId, patientId, studyId) %>%
  head(10)

s2 <- available_samples("prad_msk_2019") %>%
  select(sampleId,  patientId, studyId) %>%
  head(10)

df_pairs <- bind_rows(s1, s2) %>%
  select(-patientId)
df_pairs <- df_pairs %>%
  rename("sample_id" = sampleId,
         "study_id" = studyId)
all_genomic <- get_fusions_by_sample(sample_study_pairs = df_pairs,
                                     add_hugo = F)

**Comment by karissawhiting** [comment]
Thanks @hfuchs5 . Unfortunately, I think Hugo Symbol is still there with `add_hugo = F` it's just called `site1HugoSymbol` in that example (below), but lmk if not. 

I think I'm going to go ahead and remove this argument as it's not needed anymore.  Thanks for finding this!

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(cbioportalR)
set_cbioportal_db("public")
#> ✔ You are successfully connected!
#> ✔ base_url for this R session is now set to "www.cbioportal.org/api"

s1 <- available_samples("blca_nmibc_2017") %>%
  select(sampleId, patientId, studyId) %>%
  head(10)

s2 <- available_samples("prad_msk_2019") %>%
  select(sampleId, patientId, studyId) %>%
  head(10)

df_pairs <- bind_rows(s1, s2) %>%
  select(-patientId)
df_pairs <- df_pairs %>%
  rename("sample_id" = sampleId,
         "study_id" = studyId)
all_genomic <- get_fusions_by_sample(sample_study_pairs = df_pairs,
                                     add_hugo = F)
#> Joining, by = "study_id"
#> The following parameters were used in query:
#> Study ID: "blca_nmibc_2017" and "prad_msk_2019"
#> Molecular Profile ID: blca_nmibc_2017_structural_variants and
#> prad_msk_2019_structural_variants
#> Genes: "All available genes"

names(all_genomic)
#>  [1] "uniqueSampleKey"          "uniquePatientKey"        
#>  [3] "molecularProfileId"       "sampleId"                
#>  [5] "patientId"                "studyId"                 
#>  [7] "site1EntrezGeneId"        "site1HugoSymbol"         
#>  [9] "site1EnsemblTranscriptId" "site1Chromosome"         
#> [11] "site1Position"            "site1Contig"             
#> [13] "site1Region"              "site1RegionNumber"       
#> [15] "site1Description"         "site2EntrezGeneId"       
#> [17] "site2HugoSymbol"          "site2EnsemblTranscriptId"
#> [19] "site2Chromosome"          "site2Position"           
#> [21] "site2Contig"              "site2Region"             
#> [23] "site2RegionNumber"        "site2Description"        
#> [25] "site2EffectOnFrame"       "ncbiBuild"               
#> [27] "dnaSupport"               "rnaSupport"              
#> [29] "normalReadCount"          "tumorReadCount"          
#> [31] "normalVariantCount"       "tumorVariantCount"       
#> [33] "normalPairedEndReadCount" "tumorPairedEndReadCount" 
#> [35] "normalSplitReadCount"     "tumorSplitReadCount"     
#> [37] "annotation"               "breakpointType"          
#> [39] "connectionType"           "eventInfo"               
#> [41] "variantClass"             "length"                  
#> [43] "comments"                 "svStatus"
```

<sup>Created on 2022-08-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by alrein-05** [comment]
Hi Karissa! I noticed when using the get_genetics_by_sample() function, it does not seem to subset according to panel or genes that I input

i.e.: 
get_genetics_by_sample(sample_id=molecular$SAMPLEID[1:40], panel = c('IMPACT505'), genes = c(4609,4683))

gives the same results as 

get_genetics_by_sample(sample_id=molecular$SAMPLEID[1:40], panel = c('IMPACT505','IMPACT341'), genes = c(4609,4683))

**Comment by alrein-05** [comment]
Also noticed this for the get_structural_variants_by_sample() function!

**Comment by karissawhiting** [comment]
Hey @alrein-05 thanks for the feedback! When both `panel` and `genes` are passed, the function will default to returning the intersection of the two. I think this current behavior could be useful if you want to query an entire panel plus another few additional genes of interests, but this definitely should be better documented, so I will add more info in the function description!

**Comment by karissawhiting** [comment]
- Fixed and kept `add_hugo` argument but clarified documentation that `add_hugo = FALSE`  will not remove columns, only inhibit behavior of adding them if they are not present by default. 
- Clarified documentation on panel/gene arguments. Added in vignette that this is for functions that pull by sample.
