### ISSUE TITLE
available_studies() API request failed 404

### ISSUE THREAD

**Issue by ypradat** [karissawhiting/cbioportalR#70]
Dear @karissawhiting,

Thank you so much for developing such a practical package for requesting cbioportal instances.

The first command in the tutorial ran smoothly though

```
>   set_cbioportal_db("public")
✔ You are successfully connected!
✔ base_url for this R session is now set to "www.cbioportal.org/api"
```

but not the second example command,

```
>   available_studies()
Error: API request failed: 404
```

I installed cbioportalR within a conda environment which has R v4.2.0 installed and ran the command `mamba install bioconductor-cbioportalr` to install the package.  Checking the version installed tells me its v1.1.0

```
> conda list | grep "cbioportalr"
r-cbioportalr             1.1.0             r42hc72bb7e_0    conda-forge
```

I am on a macOS with M2 apple silicon chips.

Best regards,
Yoann Pradat

**Comment by ypradat** [comment]
Hello again,

The issue can be solved by replaced `studies/` by `studies` here https://github.com/karissawhiting/cbioportalR/blob/main/R/by_database.R#L18.

Best regards,
Yoann Pradat

**Comment by karissawhiting** [comment]
Hi @ypradat! Thank you for identifying this bug and suggesting a change. Looks like the routing rules/rules for trailing slashes changed with the recent updates in the underlying cbioportal API.

A fix has been pushed to a dev package version, available on the main branch here. We will create a cran release that includes this fix soon.

Thanks!
