### ISSUE TITLE
available_studies()

### ISSUE THREAD

**Issue by kmezhoud** [karissawhiting/cbioportalR#72]
Hi,
Please, check with me this error.
Thanks
```{r}
> library(cbioportalR)
> set_cbioportal_db("public")
✔ You are successfully connected!
✔ base_url for this R session is now set to "www.cbioportal.org/api" 
> test_cbioportal_db()
✔ You are successfully connected!
> available_studies()
Error: API request failed: 404
``` 
Karim

**Comment by karissawhiting** [comment]
Hi @kmezhoud !

This was due to a temporary bug in the underlying cbioportal API that occurred when they updated. It should be fixed now, but let me know if you're still having issues.
