### ISSUE TITLE
get_study_info() refers to incorrect function

### ISSUE THREAD

**Issue by clarrity** [karissawhiting/cbioportalR#73]
```
cbioportalR::get_study_info()
Error in `.check_for_study_id()`:
! You must provide a `study_id`. See `get_studies()` to view available studies on your database
cbioportalR::get_studies()
Error: 'get_studies' is not an exported object from 'namespace:cbioportalR'
cbioportalR::available_studies()
# A tibble: 399 × 13
   studyId         name  description publicStudy pmid  citation groups status importDate allSampleCount
   <chr>           <chr> <chr>       <lgl>       <chr> <chr>    <chr>   <int> <chr>               <int>
 1 acbc_mskcc_2015 Aden… Whole exom… TRUE        2609… Martelo… ACYC;…      0 2023-12-0…             12
 2 acyc_mskcc_2013 Aden… Whole-exom… TRUE        2368… Ho et a… ACYC;…      0 2023-12-0…             60
 3 acyc_fmi_2014   Aden… Targeted S… TRUE        2441… Ross et… ACYC;…      0 2023-12-0…             28
 4 acyc_jhu_2016   Aden… Whole-geno… TRUE        2686… Rettig … ACYC;…      0 2023-12-0…             25
 5 acyc_mda_2015   Aden… WGS of 21 … TRUE        2663… Mitani … ACYC;…      0 2023-12-0…            102
 6 acyc_mgh_2016   Aden… Whole-geno… TRUE        2682… Drier e… ACYC        0 2023-12-0…             10
 7 acyc_sanger_20… Aden… Whole exom… TRUE        2377… Stephen… ACYC;…      0 2023-12-0…             24
 8 acc_2019        Aden… Multi-Inst… TRUE        3148… Allen e… ACYC;…      0 2023-12-0…           1049
 9 bcc_unige_2016  Basa… Whole-exom… TRUE        2695… Bonilla… PUBLIC      0 2023-12-0…            293
10 all_stjude_2015 Acut… Comprehens… TRUE        2573… Anderss… PUBLIC      0 2023-12-0…             93
```

I think the "get_studies()" should be replaced with "available_studies()".

**Comment by karissawhiting** [comment]
Hi @clarrity,

I named the functions in this way to distinguish the primary ways users may interact with the database: 

1. browsing/seeing what's available (`available_*()`) and 
2. pulling data for specific items in the database (`get_*()`). 

In the above case, a user can see what studies are available in the database for data extraction using `cbioportalR::available_studies()`. Then, once they've selected a study they are interested in, they can use `get_study_info(<a select study_id>)` which will return the metadata for that particular study. From there, they may want to browse what clinical data (`available_clinical_attributes(<a select study_id>)`) or molecular data is available (`available_profiles(<a select study_id>)`) for that select study, etc. 

Here's some additional  info on guiding principles used in development of {cbioportalR} if you're interested: https://www.karissawhiting.com/cbioportalR/articles/internal-structure.html 

Thanks for using {cbioportalR}!

**Comment by clarrity** [comment]
I have used that functionality before and it works well. What I was referring to , is that the return says 
`! You must provide a `study_id`. See `get_studies()` to view available studies on your database`
but when I try using the command `get_studies()`, this command is not exported from the package.
The command that lists the studies availble , which then allows me to find the correct study ID, is actually `available_studies()`.
