### ISSUE TITLE
Could not connect to Genie db

### ISSUE THREAD

**Issue by Almogkm** [karissawhiting/cbioportalR#74]
I keep getting this error: 

> > set_cbioportal_db()
> Error in `value[[3L]]()`:
> ! Not able to connect to "genie.cbioportal.org/api"
> Backtrace:
>  1. cbioportalR::set_cbioportal_db()
>  2. cbioportalR::test_cbioportal_db()
>  3. base::tryCatch(...)
>  4. base (local) tryCatchList(expr, classes, parentenv, handlers)
>  5. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
>  6. value[[3L]](cond)

I've tried a new token, I've tried reinstalling the package.

**Comment by karissawhiting** [comment]
Hi @Almogkm

This was a temporary issue in the underlying genie cbioportal API that occurred when they updated it, and it should be resolved now. Please let me know if you are still experiencing issues!

Thanks.
