### ISSUE TITLE
Download GENIE BPC CRC v2.0-public

### ISSUE THREAD

**Issue by drhmoosavi** [karissawhiting/cbioportalR#75]
Hi,
I am trying to access this public data set **`https://genie.cbioportal.org/study/summary?id=crc_public_genie_bpc`**. But it seems Genie datasets are not returned via `cbioportalR::available_studies()` using `set_cbioportal_db("public")`.

Any tips on how to retrieve clinical and genomic data? synapser R package is not working at the moment.
Best,

Hossein

**Comment by karissawhiting** [comment]
Hi @drhmoosavi !

Thanks for using the package. 

The GENIE data is not on the public cBioPortal account and requires a token. First, login to your cBioPortal GENIE account on a browser (`https://genie.cbioportal.org`). Once logged in, go to upper right, click on your username, and click `Data Access Token` in the drop down menu. Download the token, then copy it to clipboard, and save it to the `.Renviron` file on your computer (you can access this file easily by typing `usethis::edit_r_environ()` in Rstudio). Save it in the following format in that file:
![Screenshot 2024-07-22 at 11 36 17 AM](https://github.com/user-attachments/assets/894831ef-ecb8-4622-bd6e-c9c266309d77)

Then **restart your R session**. After you restart, you should be able to use `set_cbioportal_db("https://genie.cbioportal.org")` and you should be good to go to access all GENIE data using cbioportalR functions as you would public data.

Note, you only need to set your token once, and it should be good until it expires (1 month-ish)

Good luck!
