### ISSUE TITLE
Unable to connect to the internal MSK API

### ISSUE THREAD

**Issue by jgarces02** [karissawhiting/cbioportalR#76]
Hi there, 

I'm having some new problems (none of them happened some months ago) with this code. Am I mis-considering something? Working either on-site or through VPN.

Thanks in advance!

```
> Sys.setenv(CBIOPORTAL_TOKEN = "mytoken")
> set_cbioportal_db(db = "msk")
Error in `value[[3L]]()`:
! Not able to connect to "cbioportal.mskcc.org/api"
```

**Comment by karissawhiting** [comment]
Hi @jgarces02, is it possible your token is expired? They expire every month or so. Try grabbing a new one on the portal, entering in R environ, restarting R. Lmk if that doesn't work, thanks.

**Comment by jgarces02** [comment]
Thanks @karissawhiting. I already tried it and it didn't work. Curiously, the token didn't change from before the summer to now. Maybe I'm doing something wrong? (I just downloaded it from the [cBioportal web](https://docs.cbioportal.org/deployment/authorization-and-authentication/authenticating-users-via-tokens/#using-data-access-tokens)).

**Comment by karissawhiting** [comment]
Can you confirm you are getting your token when you are logged into cbioportal.mskcc.org ? Can you try putting it in your .Renviron file (use `usethis::edit_r_environ()`) , then restart R and just try the code `set_cbioportal_db(db = "msk")` only?
